version: 2.0.{build}
image: Visual Studio 2022
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
configuration: Release
before_build:
- ps: dotnet restore
build:
  verbosity: minimal
test_script:
- ps: >-
    cd tests/Preconditions.Tests/
    
    dotnet test
    
    cd ../..
after_test:
- ps: >-
    cd src/Preconditions
    
    dotnet pack
    
    cd ../..
artifacts:
- path: '**\*.nupkg'
